### ISSUE TITLE
[dependency-submission] Gradle 8.7-rc-1 incompatibility

### ISSUE THREAD

**Issue by ben-manes** [gradle/actions#53]
```console
Caused by: org.gradle.internal.exceptions.DefaultMultiCauseException: The dependency-graph extractor plugin encountered errors while extracting dependencies. Please report this issue at: https://github.com/gradle/github-dependency-graph-gradle-plugin/issues
	at org.gradle.dependencygraph.extractor.DependencyExtractor.close(DependencyExtractor.kt:296)
	at org.gradle.api.services.internal.RegisteredBuildServiceProvider.lambda$maybeStop$1(RegisteredBuildServiceProvider.java:168)
	... 133 more
Caused by: java.lang.IllegalStateException: buildOperation.details & finishedEvent.result were unexpected types
	at org.gradle.dependencygraph.extractor.DependencyExtractor.finished(DependencyExtractor.kt:337)
	at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildOperationListener.handle(DefaultBuildEventsListenerRegistry.java:234)
	at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildOperationListener.handle(DefaultBuildEventsListenerRegistry.java:211)
	at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$AbstractListener.run(DefaultBuildEventsListenerRegistry.java:180)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	... 5 more
```

https://github.com/ben-manes/caffeine/actions/runs/8033070787/job/21943169140

**Comment by erichaagdev** [comment]
Thanks for the report @ben-manes! I was able to recreate this locally.

https://ge.solutions-team.gradle.com/s/deewltzjdm27s/failure#1

I will continue to investigate it.

**Comment by ben-manes** [comment]
oh, it's odd that dependabot did not try to send an upgrade request for the action, and even claims there are none when telling it to run explicitly for actions.

Sadly this still failed
- [github action](https://github.com/ben-manes/caffeine/actions/runs/8077027708/job/22066519413)
- [buildscan](https://caffeine.gradle-enterprise.cloud/s/bmfy2f2bawkve)

```
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Configuration cache state could not be cached: field `value` of `org.gradle.internal.Try$Success` bean found in field `result` of `org.gradle.internal.serialization.Cached$Fixed` bean found in field `configurationResolvers` of task `:jcache:ForceDependencyResolutionPlugin_resolveProjectDependencies` of type `org.gradle.forceresolve.ResolveProjectDependenciesTask`: error writing value of type 'java.util.ArrayList'
> Could not create task ':jcache:jar'.
   > Could not create an instance of type aQute.bnd.gradle.BundleTaskExtension.
      > Cannot change attributes of configuration ':jcache:compileClasspath' after it has been locked for mutation
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org./
==============================================================================
2: Task failed with an exception.
-----------
* What went wrong:
Failed to notify build listener.
> Could not create task ':jcache:jar'.
   > Could not create an instance of type aQute.bnd.gradle.BundleTaskExtension.
      > Cannot change attributes of configuration ':jcache:compileClasspath' after it has been locked for mutation
> Failed to stop service 'dependencyExtractorService'.
   > The dependency-graph extractor plugin encountered errors while extracting dependencies. Please report this issue at: https://github.com/gradle/github-dependency-graph-gradle-plugin/issues
      > Could not create task ':jcache:jar'.
         > Could not create an instance of type aQute.bnd.gradle.BundleTaskExtension.
            > Cannot change attributes of configuration ':jcache:compileClasspath' after it has been locked for mutation
```

**Comment by bigdaz** [comment]
Thanks Ben. At least that makes the underlying exception clearer.

**Comment by ben-manes** [comment]
I tried upgrading to bnd 7.0 and it [worked](https://github.com/ben-manes/caffeine/actions/runs/8085015306). The bnd plugin switched to requiring that Gradle runs on Java 17 minimum, so a few other changes in that commit.

If that's an appropriate fix then you can close this.

**Comment by ben-manes** [comment]
This upgrade is [merged](https://github.com/ben-manes/caffeine/commit/151774f77142bee3aa3ffbec030ff9790e4d6f3f) to master. I'm not sure if the bnd problem is a regression worth investigating, but from my side this can be closed.

**Comment by erichaagdev** [comment]
Hi @ben-manes. Thank you for the update. I agree that it might be worth investigating why that version of `bnd` made dependency submission fail. Since this occurrence is resolved I will go ahead and close this issue.
